### ISSUE TITLE
Kinematic Rigidbody does not work with the grabber

### ISSUE THREAD

**Issue by ROBYER1** [immemorable-moniker/UnityXRGrabAndClimb#2]
I'm not too sure why marking a rigidbody as 'kinematic' makes it unselectable with the grabber script. Great work on the inputs though, something that doesn't need any specific platform SDK is just what I've been looking for!

**Comment by jackpritz** [comment]
When an object is grabbed, a physics joint is made. That physics joint controls movement of the grabbed object. When you make a rigidbody kinematic, it is no longer affected by physics. That is why marking a grabbable object as kinematic no longer allows you to move it.
